heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: demo-keypair
      image: ubuntu-14.04-server-amd64
      flavor: m1.small
      networks: 
        - network: demo-network